displayName=Slayer Simplified
author=Wulfic
description=Slayer task assistant with auto-navigation, loot-tables, wiki stats, notes, and more.
tags=slayer,simplified,navigation,path,shortest
plugins=com.slayersimplified.SlayerSimplifiedPlugin
build=gradle