displayName=Slayer Simplified
author=Wulfic
description=Slayer task assistant with auto-navigation, loot-tables, wiki stats, notes, history, and more.
tags=slayer,simplified,navigation,path,shortest,task
plugins=com.slayersimplified.SlayerSimplifiedPlugin
build=standard